name: Release
on:
  push:
  create:
    tags:
      - anzen-v*
  
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install autoconf libleptonica-dev -y
      - name: Build
        run: |
          ./autogen.sh
          mkdir -p build build-out
          cd build
          ../configure --disable-openmp --prefix=$(realpath ../build-out)
          make && make install
          cd ..
      - name: Save output
        uses: actions/upload-artifact@v4
        with:
          name: anzen-tesseract-linux-amd64
          path: build-out
